#!/bin/bash

# Extract fields using jq
jq -r '[.name, .types[0].type.name, .weight, .height] | @tsv' data.json |
awk -F'\t' '{
  name = $1
  type = $2
  weight_kg = $3 / 10
  height_m = $4 / 10
  printf "%s is of type %s, weighs %.0fkg, and is %.1fm tall.\n", name, type, weight_kg, height_m
}' |
sed 's/^\(.\)/\U\1/'

