#!/bin/bash

raw_data=$(jq -r '[.name, .types[0].type.name, .weight, .height] | @tsv' data.json)

read name type weight height <<< "$raw_data"

formatted_weight=$(awk "BEGIN { printf \"%.0f\", $weight / 10 }")
formatted_height=$(awk "BEGIN { printf \"%.1f\", $height / 10 }")

type=$(echo "$type" | sed 's/.*/\u&/')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
